# Generated by Django 5.2.13 on 2026-04-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_add_verified_by_user_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(default='O+', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Male', max_length=50),
        ),
    ]
