# Generated by Django 5.2.13 on 2026-04-30 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_add_routing_fields'),
        ('patients', '0005_patientsubmission_category_and_more'),
    ]

    operations = [
    ]
