# Generated by Django 5.2.13 on 2026-05-01 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_merge_20260501_0005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VitalsLog',
        ),
    ]
