# Generated by Django 5.2.13 on 2026-05-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patientsubmission_assigned_to_staffnote_vitalslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsubmission',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
