# Generated by Django 5.2.13 on 2026-05-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patientsubmission_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_photo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
