# Generated by Django 5.2.13 on 2026-05-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_backup_and_remove_submission_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
