# Generated by Django 5.2.13 on 2026-04-28 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triage_status_change_enabled', models.BooleanField(default=True, help_text='Receive notifications when triage status changes')),
                ('priority_update_enabled', models.BooleanField(default=True, help_text='Receive notifications when priority is updated')),
                ('role_change_enabled', models.BooleanField(default=True, help_text='Receive notifications when role changes')),
                ('critical_alert_enabled', models.BooleanField(default=True, help_text='Receive critical alert notifications')),
                ('system_message_enabled', models.BooleanField(default=True, help_text='Receive system message notifications')),
                ('user', models.OneToOneField(help_text='The user these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('triage_status_change', 'Triage Status Change'), ('priority_update', 'Priority Update'), ('role_change', 'Role Change'), ('critical_alert', 'Critical Alert'), ('system_message', 'System Message')], db_index=True, help_text='The type of notification', max_length=50)),
                ('title', models.CharField(help_text='Short title for the notification (1-200 characters)', max_length=200)),
                ('message', models.CharField(help_text='Detailed message content (1-1000 characters)', max_length=1000)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data related to the notification')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether the user has read this notification')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the notification was created')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was marked as read', null=True)),
                ('user', models.ForeignKey(help_text='The user who should receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_notifications_user_created'), models.Index(fields=['user', 'is_read'], name='idx_notifications_user_read')],
            },
        ),
    ]
