# Generated by Django 6.0.4 on 2026-04-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=20)),
                ('symptoms', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('urgency_score', models.IntegerField(blank=True, null=True)),
                ('priority_level', models.IntegerField(blank=True, null=True)),
                ('queue_position', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
