# Generated by Django 5.2.13 on 2026-04-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('staff', 'Staff'), ('nurse', 'Nurse'), ('doctor', 'Doctor'), ('admin', 'Admin')], default='patient', max_length=20),
        ),
    ]
