# Generated by Django 5.2.13 on 2026-04-19 23:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_alter_patientsubmission_patient'),
        ('triage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TriageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('priority_level', models.CharField(default='normal', max_length=20)),
                ('urgency_score', models.IntegerField(default=0)),
                ('symptoms', models.TextField(blank=True)),
                ('queue_position', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_sessions', to='patients.patient')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TriageResult',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='triage_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='triage.triagesession'),
        ),
        migrations.AddField(
            model_name='airesult',
            name='triage_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_result', to='triage.triagesession'),
        ),
    ]
