# Generated by Django 5.2.13 on 2026-04-29 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='triage_session',
        ),
        migrations.RemoveField(
            model_name='triagesession',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='triagesession',
            name='staff',
        ),
        migrations.DeleteModel(
            name='AIResult',
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.DeleteModel(
            name='TriageSession',
        ),
    ]
